### ISSUE TITLE
Cannot find Mystic Light HID device 

### ISSUE THREAD

**Issue by jonaprieto** [Koromix/meestic#1]
Hey, I'm trying to use your program `meestic` on my machine MSI Delta 15. Unfortunately, it seems to not working.

```
$ uname -a
Linux fedora 5.18.9-200.fc36.x86_64 Koromix/rygel#1 SMP PREEMPT_DYNAMIC
Sat Jul 2 15:56:43 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

Can you guide me on how to get it work? I got this error:

```bash
$ ./meestic -m Disabled
Error: Cannot find Mystic Light HID device (1462:1564)
```
I have:

```
Bus 001 Device 004: ID 1462:1563 Micro Star International MysticLight MS-1563 v0001
```

For the record, the Python script found in https://gitlab.com/CalcProgrammer1/OpenRGB/-/issues/2289#note_947399598 works.

**Comment by Koromix** [comment]
Hi!

Indeed, this is a (slightly) different MysticLight controller, with a differnet VID:PID pair. But according to the OpenRGB issue you linked, it works just the same.

So I've pushed a commit that should support `MysticLight MS-1563`, and updated the binaries at https://koromix.dev/files/meestic/

Please tell me if it works :)

**Comment by jonaprieto** [comment]
I just tested it. It works like a charm.

**Comment by Koromix** [comment]
Thanks! :)
